version: '3.7'

volumes:
  symfony-logs:
  nginx-logs:

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./.data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpfpm:
    build: ./phpfpm
    volumes:
      - ${SYMFONY_APP_PATH}:/var/www/symfony
      - symfony-logs:/var/www/symfony/app/logs

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    environment:
      - NGINX_HOST=symfony.local
      - NGINX_PORT=80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/symfony.conf:/etc/nginx/conf.d/symfony.template:ro
      - ${SYMFONY_APP_PATH}:/var/www/symfony
      - nginx-logs:/var/log/nginx
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/symfony.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  elk:
    image: willdurand/elk
    ports:
      - 81:80
    volumes:
      - ./elk/logstash:/etc/logstash
      - ./elk/logstash/patterns:/opt/logstash/patterns
      - nginx-logs:/var/log/nginx
      - symfony-logs:/var/log/symfony